services:
  web:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "${WEB_PORT:-80}:80"
    volumes:
      - ./magento-src:/var/www/html
    depends_on:
      - db
      - elasticsearch
      - redis
      - rabbitmq
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003

  cron:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./magento-src:/var/www/html
    depends_on:
      - db
      - redis
    user: "www-data"
    command: bash -c "while true; do php bin/magento cron:run; sleep 60; done"

  db:
    image: mariadb:10.6
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magentopassword
    volumes:
      - db-data:/var/lib/mysql

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ES_PORT:-9200}:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  redis:
    image: redis:7.0-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - "${RMQ_PORT:-5672}:5672"
      - "${RMQ_MGMT_PORT:-15672}:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT:-8081}:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword

  mailpit:
    image: axllent/mailpit
    ports:
      - "${MAILPIT_UI_PORT:-8025}:8025"
      - "${MAILPIT_SMTP_PORT:-1025}:1025"

volumes:
  db-data:
  es-data:
  rabbitmq-data:
